version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_PORT:-2181}:2181"
    networks:
      - kafka_net

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_HTTP:-9092}:9092"
      - "${KAFKA_HTTPS:-9093}:9093"
    networks:
      - kafka_net
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED:-localhost}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT:-2181}
  
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "${KAFKAUI_PORT:-8080}:8080"
    volumes:
      - kafka_ui_data
    networks:
      - kafka_net
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=${KAFKAUI_CLUSTER_NAME:-kafka}
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

volumes:
  kafka_data: {}
  zookeeper_data: {}
  kafka_ui_data:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  kafka_net:
    driver: bridge
